### ISSUE TITLE
Clarify state of participants after they sent their weights

### ISSUE THREAD

**Issue by little-dude** [xainag/xain-fl#330] opened 2020-02-23 08:20 UTC
Between the moment a participant send their local weights and the moment the coordinator sees the participant as "done", the participant cannot just go back to "waiting", because the heartbeat responses will make it switch back to "training" right away.

**Comment by Robert-Steiner** [comment] 2020-06-24 12:29
I'm closing this issue because the issue/solution relates to an old version (`v0.8.0`) of the rust coordinator that is no longer maintained. In the upcoming version, the issue is no longer present.

**Closed by Robert-Steiner** 2020-06-24 12:29 UTC
